coverage:
  precision: 0
  round: up
  range: 60..99
  ignore:
    - "adapter/authtest/"
    - "adapter/integrationtest/"
    - "bin/"
    - "template/"
    - "apigee-istio/"
    - "context/"
    - "auth-proxy/"
