# Defines templates and a rule that connects to Apigee "helloworld" Proxy
# Configuration
#   apigeeproxy values must equal the name of a proxy you created on Apigee
#   The apikey value defines where to get the apikey - default is `apikey` header
#   The default rule below matches any Istio-enabled services
---
# instance configuration for template 'auth'
apiVersion: "config.istio.io/v1alpha2"
kind: auth
metadata:
  name: apigee
  namespace: istio-system
spec:
  apikey: request.headers["apikey"] | ""
  uripath: request.path | "/"
  apigeeproxy: '"helloworld"'
---
# instance configuration for template 'analytics'
apiVersion: "config.istio.io/v1alpha2"
kind: analytics
metadata:
  name: apigee
  namespace: istio-system
spec:
  apikey: request.headers["apikey"] | "" # HACK
  apigeeproxy: '"helloworld"' # HACK
  apigeeproxy_revision: 0 # HACK
  response_status_code: response.code | 0
  client_ip: source.ip | ip("0.0.0.0")
  request_verb: request.method | ""
  request_uri: request.path | ""
  request_path: request.path | ""
  useragent: request.useragent | ""
  client_received_start_timestamp: request.time # HACK - no ability to provide default ts values!
  client_received_end_timestamp: request.time
  target_sent_start_timestamp: request.time
  target_sent_end_timestamp: request.time
  target_received_start_timestamp: response.time
  target_received_end_timestamp: response.time
  client_sent_start_timestamp: response.time
  client_sent_end_timestamp: response.time
---
# rule: dispatch to handler 'apigee-handler'
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: apigee
  namespace: istio-system
spec:
  match: destination.labels["gateway"]=="apigee"
  actions:
  - handler: apigee-handler.apigee
    instances:
    - apigee.auth
    - apigee.analytics
---

# hack to workaround Mixer bug: deny all requests without apikey header
apiVersion: "config.istio.io/v1alpha2"
kind: denier
metadata:
  name: reject-missing-api-key
  namespace: istio-system
spec:
  status:
    code: 401
    message: Unauthorized
---
apiVersion: "config.istio.io/v1alpha2"
kind: checknothing
metadata:
  name: reject-missing-api-key
  namespace: istio-system
spec:
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: reject-missing-api-key
  namespace: istio-system
spec:
  match: (request.headers["apikey"] | "AREYOUKIDDINGME?") == "AREYOUKIDDINGME?"
  actions:
  - handler: reject-missing-api-key.denier
    instances:
    - reject-missing-api-key.checknothing
