# Defines templates and a rule that connects to Apigee "helloworld" Proxy
# Configuration
#   apigeeproxy values must equal the name of a proxy you created on Apigee
#   The apikey value defines where to get the apikey - default is `apikey` header
#   The default rule below matches any Istio-enabled services
---
# instance configuration for template 'auth'
apiVersion: "config.istio.io/v1alpha2"
kind: auth
metadata:
 name: helloworld
 namespace: istio-system
spec:
 apikey: request.headers["apikey"] | ""
 uripath: request.path | "/"
 apigeeproxy: '"helloworld"'
---
# instance configuration for template 'logentry'
apiVersion: "config.istio.io/v1alpha2"
kind: logentry
metadata:
  name: helloworld
  namespace: istio-system
spec:
  severity: '"Default"'
  timestamp: request.time
  variables:
    apikey: request.headers["apikey"] | "" # HACK
    apigeeproxy: '"helloworld"'
    response_status_code: response.code | 0
    client_ip: source.ip | ip("0.0.0.0")
    request_verb: request.method | ""
    request_uri: request.path | ""
    request_path: request.path | ""
    useragent: request.useragent | ""
    client_received_start_timestamp: request.time
    client_received_end_timestamp: request.time
    client_sent_start_timestamp: response.time
    client_sent_end_timestamp: response.time
  monitoredResourceType: '"UNSPECIFIED"'
---
# rule to dispatch to handler 'apigee-handler'
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
 name: helloworld-proxy
 namespace: istio-system
spec:
 match: "true"
 actions:
 - handler: apigee-handler.apigee
   instances:
   - helloworld.auth
   - helloworld.logentry
