load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "go_default_library",
    srcs = [
        "verify_api_key.go",
        "verify_api_key_structs.go",
    ],
    visibility = ["//visibility:public"],
    deps = [],
)
