apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apigee-adapter
  namespace: istio-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: apigee-adapter
        version: v1
    spec:
      containers:
      - name: apigee-adapter
        image: "gcr.io/apigee-api-management-istio/apigee-adapter:nightly"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: apigee-adapter
  namespace: istio-system
  labels:
    app: apigee-adapter
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: apigee-adapter
---
