# Create apid bridge for Apigee
# Configuration:
#   Apigee organization must be enabled for hybrid and a cluster must be created on Edge UI
#   All the *_server_base env values must equal the Apigee base url
#   The destination/service in the egress must match as well
#   The apid_apigeesync_consumer_key, apid_apigeesync_consumer_secret, and apid_apigeesync_cluster_id values
#     must match the values given for the cluster you created on Edge UI.
#   You may uncomment the `type: Nodeport` to have an ingress.
---
apiVersion: v1
kind: Service
metadata:
  name: apid
  namespace: istio-system
spec:
  type: NodePort # for testing only
  selector:
    app: apid
  ports:
  - name: http
    protocol: TCP
    port: 9000
    targetPort: http-api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apid
  namespace: istio-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: apid
    spec:
      containers:
      - name: apid
        image: scottganyo/apid:latest
        ports:
        - name: http-api
          containerPort: 9000
        - name: http-mgmt
          containerPort: 9000
        env:
        - name: apid_api_expvar_path
          value: /expvar
        - name: apid_apigeesync_proxy_server_base
          value: https://hybrid-eap.apigee.com/edgex
        - name: apid_apigeesync_snapshot_server_base
          value: https://hybrid-eap.apigee.com/edgex
        - name: apid_apigeesync_change_server_base
          value: https://hybrid-eap.apigee.com/edgex
        - name: apid_apidanalytics_uap_server_base
          value: https://hybrid-eap.apigee.com/edgex
        - name: apid_apigeesync_blob_server_base
          value: https://hybrid-eap.apigee.com/edgex
        - name: apid_gatewaydeploy_bundle_download_endpoint
          value: http://127.0.0.1:9000
        - name: apid_api_listen
          value: :9000
        - name: apid_log_level
          value: debug
        - name: apid_apigeesync_consumer_key
          value: uPHZn3iBMsJripILNAvDfIyBWlYGZWfT
        - name: apid_apigeesync_consumer_secret
          value: ss9M17uMWj6D7u0d
        - name: apid_apigeesync_cluster_id
          value: 3557b885-aede-4f17-9169-b31ea8d4b5d0
        readinessProbe:
          httpGet:
            path: /ready
            port: http-mgmt
          initialDelaySeconds: 1
          periodSeconds: 2
        livenessProbe:
          httpGet:
            path: /health
            port: http-mgmt
          initialDelaySeconds: 1
          periodSeconds: 2
---
apiVersion: config.istio.io/v1alpha2
kind: EgressRule
metadata:
  name: apigee-egress-rule
spec:
  destination:
    service: https://hybrid-eap.apigee.com/edgex
  ports:
    - port: 443
      protocol: https
#---
#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: apid
#  namespace: istio-system
#  annotations:
#    kubernetes.io/ingress.class: "istio"
#spec:
#  rules:
#  - http:
#      paths:
#      - path: /apid/.*
#        backend:
#          serviceName: apid
#          servicePort: 9000
#---
#apiVersion: config.istio.io/v1alpha2
#kind: RouteRule
#metadata:
#  name: rewrite-apid
#  namespace: istio-system
#spec:
#  destination:
#    name: apid
#    namespace: istio-system
#  match:
#    request:
#      headers:
#        uri:
#          prefix: /apid
#  rewrite:
#    uri: /
##  route:
##  - labels:
##      version: v1
##    weight: 100
