# Defines rules to apply the Apigee mixer adapter to requests.
# In the rule below, we are matching all requests in the Istio mesh (other than
# ingress, to avoid duplication) and applying Apigee authorization and
# analytics as defined in the apigee-handler.
# (See also: apigee-handler.yaml)
---
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: apigee-rule
  namespace: istio-system
spec:
  match: destination.labels["istio"] != "ingress"
  actions:
  - handler: apigee-handler.apigee
    instances:
    - apigee.authorization
    - apigee.analytics
