# Creates an Authentication policy and binds it to service.
# The example forces requests to the "helloworld" service to have a valid JWT.
# Configure issuer, jwks_uri, and services as appropriate.
---
# Define an Istio Auth Policy
apiVersion: config.istio.io/v1alpha2
kind: EndUserAuthenticationPolicySpec
metadata:
  name: auth-spec
  namespace: default
spec:
  jwts:
  - issuer: https://theganyo1-eval-test.apigee.net/edgemicro-auth/verifyApiKey
    jwks_uri: https://theganyo1-eval-test.apigee.net/edgemicro-auth/jwkPublicKeys
  - issuer: https://theganyo1-eval-test.apigee.net/edgemicro-auth/token
    jwks_uri: https://theganyo1-eval-test.apigee.net/edgemicro-auth/jwkPublicKeys
---
# Bind Istio Auth Policy to services
apiVersion: config.istio.io/v1alpha2
kind: EndUserAuthenticationPolicySpecBinding
metadata:
  name: auth
  namespace: default
spec:
  policies:
  - name: auth-spec
    namespace: default
  services:
  - name: helloworld
    namespace: default
