// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: template/analytics/template_instance.proto

/*
	Package analytics is a generated protocol buffer package.

	It is generated from these files:
		template/analytics/template_instance.proto

	It has these top-level messages:
		Type
		InstanceParam
*/
package analytics

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "istio.io/api/mixer/v1/template"
import istio_mixer_v1_config_descriptor "istio.io/api/mixer/v1/config/descriptor"

import strings "strings"
import reflect "reflect"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Type struct {
	ClientIp istio_mixer_v1_config_descriptor.ValueType `protobuf:"varint,2,opt,name=client_ip,json=clientIp,proto3,enum=istio.mixer.v1.config.descriptor.ValueType" json:"client_ip,omitempty"`
}

func (m *Type) Reset()                    { *m = Type{} }
func (*Type) ProtoMessage()               {}
func (*Type) Descriptor() ([]byte, []int) { return fileDescriptorTemplateInstance, []int{0} }

func (m *Type) GetClientIp() istio_mixer_v1_config_descriptor.ValueType {
	if m != nil {
		return m.ClientIp
	}
	return istio_mixer_v1_config_descriptor.VALUE_TYPE_UNSPECIFIED
}

type InstanceParam struct {
	ResponseStatusCode           string `protobuf:"bytes,1,opt,name=response_status_code,json=responseStatusCode,proto3" json:"response_status_code,omitempty"`
	ClientIp                     string `protobuf:"bytes,2,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	RequestVerb                  string `protobuf:"bytes,3,opt,name=request_verb,json=requestVerb,proto3" json:"request_verb,omitempty"`
	RequestUri                   string `protobuf:"bytes,4,opt,name=request_uri,json=requestUri,proto3" json:"request_uri,omitempty"`
	RequestPath                  string `protobuf:"bytes,5,opt,name=request_path,json=requestPath,proto3" json:"request_path,omitempty"`
	Useragent                    string `protobuf:"bytes,6,opt,name=useragent,proto3" json:"useragent,omitempty"`
	ClientReceivedStartTimestamp string `protobuf:"bytes,7,opt,name=client_received_start_timestamp,json=clientReceivedStartTimestamp,proto3" json:"client_received_start_timestamp,omitempty"`
	ClientReceivedEndTimestamp   string `protobuf:"bytes,8,opt,name=client_received_end_timestamp,json=clientReceivedEndTimestamp,proto3" json:"client_received_end_timestamp,omitempty"`
	ClientSentStartTimestamp     string `protobuf:"bytes,9,opt,name=client_sent_start_timestamp,json=clientSentStartTimestamp,proto3" json:"client_sent_start_timestamp,omitempty"`
	ClientSentEndTimestamp       string `protobuf:"bytes,10,opt,name=client_sent_end_timestamp,json=clientSentEndTimestamp,proto3" json:"client_sent_end_timestamp,omitempty"`
	TargetSentStartTimestamp     string `protobuf:"bytes,11,opt,name=target_sent_start_timestamp,json=targetSentStartTimestamp,proto3" json:"target_sent_start_timestamp,omitempty"`
	TargetSentEndTimestamp       string `protobuf:"bytes,12,opt,name=target_sent_end_timestamp,json=targetSentEndTimestamp,proto3" json:"target_sent_end_timestamp,omitempty"`
	TargetReceivedStartTimestamp string `protobuf:"bytes,13,opt,name=target_received_start_timestamp,json=targetReceivedStartTimestamp,proto3" json:"target_received_start_timestamp,omitempty"`
	TargetReceivedEndTimestamp   string `protobuf:"bytes,14,opt,name=target_received_end_timestamp,json=targetReceivedEndTimestamp,proto3" json:"target_received_end_timestamp,omitempty"`
	Apikey                       string `protobuf:"bytes,200,opt,name=apikey,proto3" json:"apikey,omitempty"`
}

func (m *InstanceParam) Reset()                    { *m = InstanceParam{} }
func (*InstanceParam) ProtoMessage()               {}
func (*InstanceParam) Descriptor() ([]byte, []int) { return fileDescriptorTemplateInstance, []int{1} }

func (m *InstanceParam) GetResponseStatusCode() string {
	if m != nil {
		return m.ResponseStatusCode
	}
	return ""
}

func (m *InstanceParam) GetClientIp() string {
	if m != nil {
		return m.ClientIp
	}
	return ""
}

func (m *InstanceParam) GetRequestVerb() string {
	if m != nil {
		return m.RequestVerb
	}
	return ""
}

func (m *InstanceParam) GetRequestUri() string {
	if m != nil {
		return m.RequestUri
	}
	return ""
}

func (m *InstanceParam) GetRequestPath() string {
	if m != nil {
		return m.RequestPath
	}
	return ""
}

func (m *InstanceParam) GetUseragent() string {
	if m != nil {
		return m.Useragent
	}
	return ""
}

func (m *InstanceParam) GetClientReceivedStartTimestamp() string {
	if m != nil {
		return m.ClientReceivedStartTimestamp
	}
	return ""
}

func (m *InstanceParam) GetClientReceivedEndTimestamp() string {
	if m != nil {
		return m.ClientReceivedEndTimestamp
	}
	return ""
}

func (m *InstanceParam) GetClientSentStartTimestamp() string {
	if m != nil {
		return m.ClientSentStartTimestamp
	}
	return ""
}

func (m *InstanceParam) GetClientSentEndTimestamp() string {
	if m != nil {
		return m.ClientSentEndTimestamp
	}
	return ""
}

func (m *InstanceParam) GetTargetSentStartTimestamp() string {
	if m != nil {
		return m.TargetSentStartTimestamp
	}
	return ""
}

func (m *InstanceParam) GetTargetSentEndTimestamp() string {
	if m != nil {
		return m.TargetSentEndTimestamp
	}
	return ""
}

func (m *InstanceParam) GetTargetReceivedStartTimestamp() string {
	if m != nil {
		return m.TargetReceivedStartTimestamp
	}
	return ""
}

func (m *InstanceParam) GetTargetReceivedEndTimestamp() string {
	if m != nil {
		return m.TargetReceivedEndTimestamp
	}
	return ""
}

func (m *InstanceParam) GetApikey() string {
	if m != nil {
		return m.Apikey
	}
	return ""
}

func init() {
	proto.RegisterType((*Type)(nil), "analytics.Type")
	proto.RegisterType((*InstanceParam)(nil), "analytics.InstanceParam")
}
func (this *Type) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*Type)
	if !ok {
		that2, ok := that.(Type)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.ClientIp != that1.ClientIp {
		return false
	}
	return true
}
func (this *InstanceParam) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*InstanceParam)
	if !ok {
		that2, ok := that.(InstanceParam)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.ResponseStatusCode != that1.ResponseStatusCode {
		return false
	}
	if this.ClientIp != that1.ClientIp {
		return false
	}
	if this.RequestVerb != that1.RequestVerb {
		return false
	}
	if this.RequestUri != that1.RequestUri {
		return false
	}
	if this.RequestPath != that1.RequestPath {
		return false
	}
	if this.Useragent != that1.Useragent {
		return false
	}
	if this.ClientReceivedStartTimestamp != that1.ClientReceivedStartTimestamp {
		return false
	}
	if this.ClientReceivedEndTimestamp != that1.ClientReceivedEndTimestamp {
		return false
	}
	if this.ClientSentStartTimestamp != that1.ClientSentStartTimestamp {
		return false
	}
	if this.ClientSentEndTimestamp != that1.ClientSentEndTimestamp {
		return false
	}
	if this.TargetSentStartTimestamp != that1.TargetSentStartTimestamp {
		return false
	}
	if this.TargetSentEndTimestamp != that1.TargetSentEndTimestamp {
		return false
	}
	if this.TargetReceivedStartTimestamp != that1.TargetReceivedStartTimestamp {
		return false
	}
	if this.TargetReceivedEndTimestamp != that1.TargetReceivedEndTimestamp {
		return false
	}
	if this.Apikey != that1.Apikey {
		return false
	}
	return true
}
func (this *Type) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&analytics.Type{")
	s = append(s, "ClientIp: "+fmt.Sprintf("%#v", this.ClientIp)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *InstanceParam) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 19)
	s = append(s, "&analytics.InstanceParam{")
	s = append(s, "ResponseStatusCode: "+fmt.Sprintf("%#v", this.ResponseStatusCode)+",\n")
	s = append(s, "ClientIp: "+fmt.Sprintf("%#v", this.ClientIp)+",\n")
	s = append(s, "RequestVerb: "+fmt.Sprintf("%#v", this.RequestVerb)+",\n")
	s = append(s, "RequestUri: "+fmt.Sprintf("%#v", this.RequestUri)+",\n")
	s = append(s, "RequestPath: "+fmt.Sprintf("%#v", this.RequestPath)+",\n")
	s = append(s, "Useragent: "+fmt.Sprintf("%#v", this.Useragent)+",\n")
	s = append(s, "ClientReceivedStartTimestamp: "+fmt.Sprintf("%#v", this.ClientReceivedStartTimestamp)+",\n")
	s = append(s, "ClientReceivedEndTimestamp: "+fmt.Sprintf("%#v", this.ClientReceivedEndTimestamp)+",\n")
	s = append(s, "ClientSentStartTimestamp: "+fmt.Sprintf("%#v", this.ClientSentStartTimestamp)+",\n")
	s = append(s, "ClientSentEndTimestamp: "+fmt.Sprintf("%#v", this.ClientSentEndTimestamp)+",\n")
	s = append(s, "TargetSentStartTimestamp: "+fmt.Sprintf("%#v", this.TargetSentStartTimestamp)+",\n")
	s = append(s, "TargetSentEndTimestamp: "+fmt.Sprintf("%#v", this.TargetSentEndTimestamp)+",\n")
	s = append(s, "TargetReceivedStartTimestamp: "+fmt.Sprintf("%#v", this.TargetReceivedStartTimestamp)+",\n")
	s = append(s, "TargetReceivedEndTimestamp: "+fmt.Sprintf("%#v", this.TargetReceivedEndTimestamp)+",\n")
	s = append(s, "Apikey: "+fmt.Sprintf("%#v", this.Apikey)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringTemplateInstance(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *Type) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Type) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.ClientIp != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintTemplateInstance(dAtA, i, uint64(m.ClientIp))
	}
	return i, nil
}

func (m *InstanceParam) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *InstanceParam) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.ResponseStatusCode) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintTemplateInstance(dAtA, i, uint64(len(m.ResponseStatusCode)))
		i += copy(dAtA[i:], m.ResponseStatusCode)
	}
	if len(m.ClientIp) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintTemplateInstance(dAtA, i, uint64(len(m.ClientIp)))
		i += copy(dAtA[i:], m.ClientIp)
	}
	if len(m.RequestVerb) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintTemplateInstance(dAtA, i, uint64(len(m.RequestVerb)))
		i += copy(dAtA[i:], m.RequestVerb)
	}
	if len(m.RequestUri) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintTemplateInstance(dAtA, i, uint64(len(m.RequestUri)))
		i += copy(dAtA[i:], m.RequestUri)
	}
	if len(m.RequestPath) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintTemplateInstance(dAtA, i, uint64(len(m.RequestPath)))
		i += copy(dAtA[i:], m.RequestPath)
	}
	if len(m.Useragent) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintTemplateInstance(dAtA, i, uint64(len(m.Useragent)))
		i += copy(dAtA[i:], m.Useragent)
	}
	if len(m.ClientReceivedStartTimestamp) > 0 {
		dAtA[i] = 0x3a
		i++
		i = encodeVarintTemplateInstance(dAtA, i, uint64(len(m.ClientReceivedStartTimestamp)))
		i += copy(dAtA[i:], m.ClientReceivedStartTimestamp)
	}
	if len(m.ClientReceivedEndTimestamp) > 0 {
		dAtA[i] = 0x42
		i++
		i = encodeVarintTemplateInstance(dAtA, i, uint64(len(m.ClientReceivedEndTimestamp)))
		i += copy(dAtA[i:], m.ClientReceivedEndTimestamp)
	}
	if len(m.ClientSentStartTimestamp) > 0 {
		dAtA[i] = 0x4a
		i++
		i = encodeVarintTemplateInstance(dAtA, i, uint64(len(m.ClientSentStartTimestamp)))
		i += copy(dAtA[i:], m.ClientSentStartTimestamp)
	}
	if len(m.ClientSentEndTimestamp) > 0 {
		dAtA[i] = 0x52
		i++
		i = encodeVarintTemplateInstance(dAtA, i, uint64(len(m.ClientSentEndTimestamp)))
		i += copy(dAtA[i:], m.ClientSentEndTimestamp)
	}
	if len(m.TargetSentStartTimestamp) > 0 {
		dAtA[i] = 0x5a
		i++
		i = encodeVarintTemplateInstance(dAtA, i, uint64(len(m.TargetSentStartTimestamp)))
		i += copy(dAtA[i:], m.TargetSentStartTimestamp)
	}
	if len(m.TargetSentEndTimestamp) > 0 {
		dAtA[i] = 0x62
		i++
		i = encodeVarintTemplateInstance(dAtA, i, uint64(len(m.TargetSentEndTimestamp)))
		i += copy(dAtA[i:], m.TargetSentEndTimestamp)
	}
	if len(m.TargetReceivedStartTimestamp) > 0 {
		dAtA[i] = 0x6a
		i++
		i = encodeVarintTemplateInstance(dAtA, i, uint64(len(m.TargetReceivedStartTimestamp)))
		i += copy(dAtA[i:], m.TargetReceivedStartTimestamp)
	}
	if len(m.TargetReceivedEndTimestamp) > 0 {
		dAtA[i] = 0x72
		i++
		i = encodeVarintTemplateInstance(dAtA, i, uint64(len(m.TargetReceivedEndTimestamp)))
		i += copy(dAtA[i:], m.TargetReceivedEndTimestamp)
	}
	if len(m.Apikey) > 0 {
		dAtA[i] = 0xc2
		i++
		dAtA[i] = 0xc
		i++
		i = encodeVarintTemplateInstance(dAtA, i, uint64(len(m.Apikey)))
		i += copy(dAtA[i:], m.Apikey)
	}
	return i, nil
}

func encodeVarintTemplateInstance(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Type) Size() (n int) {
	var l int
	_ = l
	if m.ClientIp != 0 {
		n += 1 + sovTemplateInstance(uint64(m.ClientIp))
	}
	return n
}

func (m *InstanceParam) Size() (n int) {
	var l int
	_ = l
	l = len(m.ResponseStatusCode)
	if l > 0 {
		n += 1 + l + sovTemplateInstance(uint64(l))
	}
	l = len(m.ClientIp)
	if l > 0 {
		n += 1 + l + sovTemplateInstance(uint64(l))
	}
	l = len(m.RequestVerb)
	if l > 0 {
		n += 1 + l + sovTemplateInstance(uint64(l))
	}
	l = len(m.RequestUri)
	if l > 0 {
		n += 1 + l + sovTemplateInstance(uint64(l))
	}
	l = len(m.RequestPath)
	if l > 0 {
		n += 1 + l + sovTemplateInstance(uint64(l))
	}
	l = len(m.Useragent)
	if l > 0 {
		n += 1 + l + sovTemplateInstance(uint64(l))
	}
	l = len(m.ClientReceivedStartTimestamp)
	if l > 0 {
		n += 1 + l + sovTemplateInstance(uint64(l))
	}
	l = len(m.ClientReceivedEndTimestamp)
	if l > 0 {
		n += 1 + l + sovTemplateInstance(uint64(l))
	}
	l = len(m.ClientSentStartTimestamp)
	if l > 0 {
		n += 1 + l + sovTemplateInstance(uint64(l))
	}
	l = len(m.ClientSentEndTimestamp)
	if l > 0 {
		n += 1 + l + sovTemplateInstance(uint64(l))
	}
	l = len(m.TargetSentStartTimestamp)
	if l > 0 {
		n += 1 + l + sovTemplateInstance(uint64(l))
	}
	l = len(m.TargetSentEndTimestamp)
	if l > 0 {
		n += 1 + l + sovTemplateInstance(uint64(l))
	}
	l = len(m.TargetReceivedStartTimestamp)
	if l > 0 {
		n += 1 + l + sovTemplateInstance(uint64(l))
	}
	l = len(m.TargetReceivedEndTimestamp)
	if l > 0 {
		n += 1 + l + sovTemplateInstance(uint64(l))
	}
	l = len(m.Apikey)
	if l > 0 {
		n += 2 + l + sovTemplateInstance(uint64(l))
	}
	return n
}

func sovTemplateInstance(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozTemplateInstance(x uint64) (n int) {
	return sovTemplateInstance(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *Type) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Type{`,
		`ClientIp:` + fmt.Sprintf("%v", this.ClientIp) + `,`,
		`}`,
	}, "")
	return s
}
func (this *InstanceParam) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&InstanceParam{`,
		`ResponseStatusCode:` + fmt.Sprintf("%v", this.ResponseStatusCode) + `,`,
		`ClientIp:` + fmt.Sprintf("%v", this.ClientIp) + `,`,
		`RequestVerb:` + fmt.Sprintf("%v", this.RequestVerb) + `,`,
		`RequestUri:` + fmt.Sprintf("%v", this.RequestUri) + `,`,
		`RequestPath:` + fmt.Sprintf("%v", this.RequestPath) + `,`,
		`Useragent:` + fmt.Sprintf("%v", this.Useragent) + `,`,
		`ClientReceivedStartTimestamp:` + fmt.Sprintf("%v", this.ClientReceivedStartTimestamp) + `,`,
		`ClientReceivedEndTimestamp:` + fmt.Sprintf("%v", this.ClientReceivedEndTimestamp) + `,`,
		`ClientSentStartTimestamp:` + fmt.Sprintf("%v", this.ClientSentStartTimestamp) + `,`,
		`ClientSentEndTimestamp:` + fmt.Sprintf("%v", this.ClientSentEndTimestamp) + `,`,
		`TargetSentStartTimestamp:` + fmt.Sprintf("%v", this.TargetSentStartTimestamp) + `,`,
		`TargetSentEndTimestamp:` + fmt.Sprintf("%v", this.TargetSentEndTimestamp) + `,`,
		`TargetReceivedStartTimestamp:` + fmt.Sprintf("%v", this.TargetReceivedStartTimestamp) + `,`,
		`TargetReceivedEndTimestamp:` + fmt.Sprintf("%v", this.TargetReceivedEndTimestamp) + `,`,
		`Apikey:` + fmt.Sprintf("%v", this.Apikey) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringTemplateInstance(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *Type) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTemplateInstance
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Type: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Type: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientIp", wireType)
			}
			m.ClientIp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTemplateInstance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ClientIp |= (istio_mixer_v1_config_descriptor.ValueType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTemplateInstance(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTemplateInstance
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *InstanceParam) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTemplateInstance
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: InstanceParam: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: InstanceParam: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResponseStatusCode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTemplateInstance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTemplateInstance
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ResponseStatusCode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientIp", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTemplateInstance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTemplateInstance
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClientIp = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestVerb", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTemplateInstance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTemplateInstance
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequestVerb = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestUri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTemplateInstance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTemplateInstance
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequestUri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestPath", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTemplateInstance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTemplateInstance
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequestPath = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Useragent", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTemplateInstance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTemplateInstance
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Useragent = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientReceivedStartTimestamp", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTemplateInstance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTemplateInstance
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClientReceivedStartTimestamp = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientReceivedEndTimestamp", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTemplateInstance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTemplateInstance
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClientReceivedEndTimestamp = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientSentStartTimestamp", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTemplateInstance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTemplateInstance
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClientSentStartTimestamp = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientSentEndTimestamp", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTemplateInstance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTemplateInstance
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClientSentEndTimestamp = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetSentStartTimestamp", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTemplateInstance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTemplateInstance
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TargetSentStartTimestamp = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetSentEndTimestamp", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTemplateInstance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTemplateInstance
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TargetSentEndTimestamp = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetReceivedStartTimestamp", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTemplateInstance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTemplateInstance
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TargetReceivedStartTimestamp = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetReceivedEndTimestamp", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTemplateInstance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTemplateInstance
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TargetReceivedEndTimestamp = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 200:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Apikey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTemplateInstance
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTemplateInstance
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Apikey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTemplateInstance(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTemplateInstance
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTemplateInstance(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTemplateInstance
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTemplateInstance
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTemplateInstance
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthTemplateInstance
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowTemplateInstance
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipTemplateInstance(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthTemplateInstance = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTemplateInstance   = fmt.Errorf("proto: integer overflow")
)

func init() {
	proto.RegisterFile("template/analytics/template_instance.proto", fileDescriptorTemplateInstance)
}

var fileDescriptorTemplateInstance = []byte{
	// 522 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0x3f, 0x6f, 0xd3, 0x40,
	0x18, 0xc6, 0x73, 0xa5, 0x84, 0xfa, 0xfa, 0x67, 0x38, 0x21, 0x30, 0x69, 0xb9, 0x94, 0x4c, 0x15,
	0x95, 0x6c, 0x5a, 0x26, 0x06, 0x06, 0x40, 0x91, 0xe8, 0x16, 0x25, 0xa5, 0xab, 0x75, 0xb1, 0x5f,
	0xd2, 0x13, 0xc9, 0xf9, 0xb8, 0xbb, 0x44, 0xcd, 0xc6, 0xc0, 0x07, 0x40, 0xe2, 0x4b, 0xf0, 0x51,
	0x3a, 0x56, 0x4c, 0x8c, 0xc4, 0x30, 0x30, 0x76, 0x64, 0x44, 0xb9, 0x73, 0xe2, 0xd8, 0x22, 0x83,
	0x2d, 0xdd, 0xfb, 0x3e, 0xcf, 0xef, 0x79, 0xef, 0x95, 0x8d, 0x9f, 0x1a, 0x18, 0xc9, 0x21, 0x33,
	0x10, 0x32, 0xc1, 0x86, 0x53, 0xc3, 0x63, 0x1d, 0x2e, 0x4a, 0x11, 0x17, 0xda, 0x30, 0x11, 0x43,
	0x20, 0x55, 0x6a, 0x52, 0xe2, 0x2d, 0x25, 0x8d, 0xd6, 0x88, 0x5f, 0x81, 0x0a, 0x27, 0x27, 0x4b,
	0x71, 0x08, 0x57, 0x06, 0x84, 0xe6, 0xa9, 0xd0, 0x4e, 0xde, 0x38, 0x5e, 0x6a, 0xe2, 0x54, 0xbc,
	0xe7, 0x83, 0x30, 0x01, 0x1d, 0x2b, 0x2e, 0x4d, 0xaa, 0xc2, 0x09, 0x1b, 0x8e, 0x21, 0x32, 0x53,
	0x99, 0xb3, 0x5b, 0x1d, 0xbc, 0x79, 0x3e, 0x95, 0x40, 0xde, 0x62, 0x2f, 0x1e, 0x72, 0x10, 0x26,
	0xe2, 0xd2, 0xdf, 0x38, 0x44, 0x47, 0x7b, 0xa7, 0xc7, 0x01, 0xd7, 0x86, 0xa7, 0x81, 0xc5, 0x05,
	0x93, 0x93, 0xc0, 0xe1, 0x82, 0x02, 0x17, 0x5c, 0xcc, 0x71, 0x73, 0x7f, 0x77, 0xcb, 0xb9, 0xcf,
	0x64, 0xeb, 0x73, 0x1d, 0xef, 0x9e, 0xe5, 0x17, 0xe8, 0x30, 0xc5, 0x46, 0xe4, 0x19, 0xbe, 0xaf,
	0x40, 0xcb, 0x54, 0x68, 0x88, 0xb4, 0x61, 0x66, 0xac, 0xa3, 0x38, 0x4d, 0xc0, 0x47, 0x87, 0xe8,
	0xc8, 0xeb, 0x92, 0x45, 0xaf, 0x67, 0x5b, 0x6f, 0xd2, 0x04, 0xc8, 0x7e, 0x75, 0x1a, 0xaf, 0x08,
	0x20, 0x4f, 0xf0, 0x8e, 0x82, 0x8f, 0x63, 0xd0, 0x26, 0x9a, 0x80, 0xea, 0xfb, 0x77, 0x6c, 0x7f,
	0x3b, 0xaf, 0x5d, 0x80, 0xea, 0x93, 0x26, 0x5e, 0x1c, 0xa3, 0xb1, 0xe2, 0xfe, 0xa6, 0x55, 0xe0,
	0xbc, 0xf4, 0x4e, 0xf1, 0x55, 0x86, 0x64, 0xe6, 0xd2, 0xbf, 0x5b, 0x62, 0x74, 0x98, 0xb9, 0x24,
	0x07, 0xd8, 0x1b, 0x6b, 0x50, 0x6c, 0x00, 0xc2, 0xf8, 0x75, 0xdb, 0x2f, 0x0a, 0xa4, 0x8d, 0x9b,
	0xf9, 0x84, 0x0a, 0x62, 0xe0, 0x13, 0x48, 0xe6, 0x57, 0x53, 0x26, 0x32, 0x7c, 0x04, 0xda, 0xb0,
	0x91, 0xf4, 0xef, 0x59, 0xcf, 0x81, 0x93, 0x75, 0x73, 0x55, 0x6f, 0x2e, 0x3a, 0x5f, 0x68, 0xc8,
	0x2b, 0xfc, 0xb8, 0x8a, 0x01, 0x91, 0xac, 0x40, 0xb6, 0x2c, 0xa4, 0x51, 0x86, 0xb4, 0x45, 0x52,
	0x20, 0x5e, 0xe2, 0xfd, 0x1c, 0xa1, 0xed, 0xab, 0x32, 0x85, 0x67, 0x01, 0xbe, 0x93, 0xf4, 0xe6,
	0x4f, 0x79, 0x82, 0x17, 0xf8, 0xd1, 0xaa, 0xbd, 0x9c, 0x8e, 0xad, 0xf9, 0x41, 0x61, 0xae, 0x26,
	0x1b, 0xa6, 0x06, 0xb0, 0x26, 0x79, 0xdb, 0x25, 0x3b, 0xc9, 0xff, 0x93, 0x57, 0xed, 0xe5, 0xe4,
	0x1d, 0x97, 0x5c, 0x98, 0x4b, 0xc9, 0x6d, 0xdc, 0xcc, 0xad, 0x6b, 0xb7, 0xbf, 0xeb, 0xb6, 0xef,
	0x64, 0xeb, 0xb7, 0x5f, 0xc5, 0x94, 0xa7, 0xd8, 0x73, 0xdb, 0x2f, 0x43, 0x4a, 0x93, 0x3c, 0xc4,
	0x75, 0x26, 0xf9, 0x07, 0x98, 0xfa, 0xd7, 0xee, 0x73, 0xce, 0x8f, 0xaf, 0x4f, 0x6f, 0x66, 0xb4,
	0xf6, 0x63, 0x46, 0x6b, 0xb7, 0x33, 0x8a, 0x3e, 0x65, 0x14, 0x7d, 0xcb, 0x28, 0xba, 0xce, 0x28,
	0xba, 0xc9, 0x28, 0xfa, 0x99, 0x51, 0xf4, 0x27, 0xa3, 0xb5, 0xdb, 0x8c, 0xa2, 0x2f, 0xbf, 0x68,
	0xed, 0xef, 0xf7, 0xdf, 0x5f, 0x37, 0x50, 0xbf, 0x6e, 0xff, 0xc9, 0xe7, 0xff, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x42, 0xce, 0xf7, 0x81, 0x1d, 0x04, 0x00, 0x00,
}
