apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apigee-adapter
  namespace: istio-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: apigee-adapter
        version: v1
    spec:
      containers:
      - name: apigee-adapter
        image: "gcr.io/apigee-api-management-istio/apigee-adapter:1.4.1"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 5000
        readinessProbe:
          exec:
            command: ["/grpc_health_probe", "-addr=:5000"]
          initialDelaySeconds: 5
        livenessProbe:
          exec:
            command: ["/grpc_health_probe", "-addr=:5000"]
          initialDelaySeconds: 10
        args:
          - --address=:5000
          - --log_output_level=default:warn,adapters:info
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: apigee-adapter
  namespace: istio-system
  labels:
    app: apigee-adapter
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: apigee-adapter
---
