# Example deployment for Apigee Adapter. 
# This will work without modiciation for SaaS.
# For Hybrid, you must uncomment and properly configure the secret volumes.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigee-adapter
  namespace: istio-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigee-adapter
  template:
    metadata:
      labels:
        app: apigee-adapter
        version: v1
    spec:
      containers:
      - name: apigee-adapter
        image: "gcr.io/apigee-api-management-istio/apigee-adapter:1.4.1"
        imagePullPolicy: IfNotPresent #Always
        env:
        - name: GODEBUG # value must be 0, as apigee does not support http 2
          value: http2client=0
        ports:
        - containerPort: 5000
        readinessProbe:
          exec:
            command: ["/grpc_health_probe", "-addr=:5000"]
          initialDelaySeconds: 5
        livenessProbe:
          exec:
            command: ["/grpc_health_probe", "-addr=:5000"]
          initialDelaySeconds: 10
        args:
          - --address=:5000
          - --log_output_level=default:warn,adapters:info
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 100Mi
      #   volumeMounts:
      #   - mountPath: /opt/apigee/customer
      #     name: cwc-volume
      #     readOnly: true
      #   - mountPath: /opt/apigee/tls
      #     name: tls-volume
      #     readOnly: true
      # volumes:
      # - name: cwc-volume
      #   secret:
      #     defaultMode: 420
      #     secretName: REPLACE ME
      # - name: tls-volume
      #   secret:
      #     defaultMode: 420
      #     secretName: REPLACE ME
---
apiVersion: v1
kind: Service
metadata:
  name: apigee-adapter
  namespace: istio-system
  labels:
    app: apigee-adapter
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: apigee-adapter
