# Creates an Authentication policy and binds it to service.
# The example forces requests to helloworld or httpbin services 
# to have a valid JWT.
# Configure issuer, jwks_uri, and services as appropriate.
---
# Define an Istio Auth Policy
apiVersion: "authentication.istio.io/v1alpha1"
kind: Policy
metadata:
  name: auth-spec
  namespace: default
spec:
  targets:
  - name: helloworld
  - name: httpbin
  peers:
#  - mtls: {}  # uncomment if you're using mTLS between services in your mesh
  origins:
  - jwt:
      issuer: REPLACE ME
      jwks_uri: REPLACE ME
  principalBinding: USE_ORIGIN
