# Example Istio handler configuration for Apigee adapter for Mixer.
# use `apigee-istio provision` to generate your own.
apiVersion: config.istio.io/v1alpha2
kind: handler
metadata:
  name: apigee-handler
  namespace: istio-system
spec:
  adapter: apigee
  connection:
    address: apigee-adapter:5000
  params:
    apigee_base: https://istioservices.apigee.net/edgemicro
    customer_base: REPLACE_ME
    hybrid_config: 
    org_name: REPLACE_ME
    env_name: REPLACE_ME
    key: REPLACE_ME
    secret: REPLACE_ME
